platform :ios, '8.0'
use_frameworks!

target 'Rosan' do
    pod 'Toast'
    pod 'AFNetworking'
    pod 'IQKeyboardManager'
    pod 'SDCycleScrollView'
    pod 'SDWebImage'
    pod 'MJRefresh'
    pod 'XXNibBridge', '~> 2.2.3'
    pod 'Masonry'
end
